version: '3.1'

services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8380:80"
    env_file:
      - .env
    depends_on:
      - db

  wp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8383:80"
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html
      - ./.data/uploads:/var/www/html/wp-content/uploads
      - ./caritas-vilnius-theme:/var/www/html/wp-content/themes/caritas-vilnius-theme
      - ./wordpress.ini:/usr/local/etc/php/conf.d/wordpress.ini
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: [ --max-allowed-packet=500M ]
    platform: linux/amd64
    restart: always
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
